In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

np.random.seed(5)

Using TensorFlow backend.


In [2]:
dataset = np.loadtxt("pima-indians-diabetes.data.csv", delimiter=",")

In [7]:
x_train = dataset[:700,0:8]
y_train = dataset[:700,8]
x_test = dataset[700:,0:8]
y_test = dataset[700:,8]

In [8]:
model = Sequential()
model.add(Dense(12, input_dim=8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [9]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [10]:
model.fit(x_train, y_train, epochs=1500, batch_size=64)

Epoch 1/1500
700/700 [==============================] - 0s 290us/step - loss: 3.8567 - acc: 0.4900
Epoch 2/1500
700/700 [==============================] - 0s 22us/step - loss: 3.2218 - acc: 0.5086
Epoch 3/1500
700/700 [==============================] - 0s 0us/step - loss: 2.5493 - acc: 0.5114
Epoch 4/1500
700/700 [==============================] - 0s 33us/step - loss: 1.9579 - acc: 0.5471
Epoch 5/1500
700/700 [==============================] - 0s 14us/step - loss: 1.5661 - acc: 0.5486
Epoch 6/1500
700/700 [==============================] - 0s 14us/step - loss: 1.3525 - acc: 0.6043
Epoch 7/1500
700/700 [==============================] - 0s 14us/step - loss: 1.2255 - acc: 0.5671
Epoch 8/1500
700/700 [==============================] - 0s 14us/step - loss: 1.1265 - acc: 0.5871
Epoch 9/1500
700/700 [==============================] - 0s 14us/step - loss: 1.0426 - acc: 0.6000
Epoch 10/1500
700/700 [==============================] - 0s 14us/step - loss: 0.9710 - acc: 0.6143
Epoch 11/1500
700/7

700/700 [==============================] - 0s 14us/step - loss: 0.5393 - acc: 0.7214
Epoch 84/1500
700/700 [==============================] - 0s 11us/step - loss: 0.5303 - acc: 0.7257
Epoch 85/1500
700/700 [==============================] - 0s 11us/step - loss: 0.5422 - acc: 0.7257
Epoch 86/1500
700/700 [==============================] - 0s 14us/step - loss: 0.5419 - acc: 0.7171
Epoch 87/1500
700/700 [==============================] - 0s 14us/step - loss: 0.5340 - acc: 0.7343
Epoch 88/1500
700/700 [==============================] - 0s 14us/step - loss: 0.5294 - acc: 0.7400
Epoch 89/1500
700/700 [==============================] - 0s 14us/step - loss: 0.5284 - acc: 0.7300
Epoch 90/1500
700/700 [==============================] - 0s 14us/step - loss: 0.5280 - acc: 0.7400
Epoch 91/1500
700/700 [==============================] - 0s 14us/step - loss: 0.5309 - acc: 0.7429
Epoch 92/1500
700/700 [==============================] - 0s 14us/step - loss: 0.5287 - acc: 0.7329
Epoch 93/1500
700/700 [=

700/700 [==============================] - 0s 11us/step - loss: 0.4984 - acc: 0.7557
Epoch 166/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4979 - acc: 0.7571
Epoch 167/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4945 - acc: 0.7486
Epoch 168/1500
700/700 [==============================] - 0s 14us/step - loss: 0.4982 - acc: 0.7686
Epoch 169/1500
700/700 [==============================] - 0s 11us/step - loss: 0.5114 - acc: 0.7457
Epoch 170/1500
700/700 [==============================] - 0s 11us/step - loss: 0.5070 - acc: 0.7471
Epoch 171/1500
700/700 [==============================] - 0s 11us/step - loss: 0.5059 - acc: 0.7600
Epoch 172/1500
700/700 [==============================] - 0s 11us/step - loss: 0.5026 - acc: 0.7486
Epoch 173/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4950 - acc: 0.7600
Epoch 174/1500
700/700 [==============================] - 0s 14us/step - loss: 0.4980 - acc: 0.7429
Epoch 175/1500


700/700 [==============================] - 0s 11us/step - loss: 0.4798 - acc: 0.7757
Epoch 248/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4757 - acc: 0.7686
Epoch 249/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4789 - acc: 0.7643
Epoch 250/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4828 - acc: 0.7671
Epoch 251/1500
700/700 [==============================] - 0s 14us/step - loss: 0.4814 - acc: 0.7686
Epoch 252/1500
700/700 [==============================] - 0s 14us/step - loss: 0.4812 - acc: 0.7686
Epoch 253/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4780 - acc: 0.7743
Epoch 254/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4774 - acc: 0.7629
Epoch 255/1500
700/700 [==============================] - 0s 14us/step - loss: 0.4764 - acc: 0.7771
Epoch 256/1500
700/700 [==============================] - 0s 14us/step - loss: 0.4713 - acc: 0.7714
Epoch 257/1500


700/700 [==============================] - 0s 14us/step - loss: 0.4635 - acc: 0.7700
Epoch 330/1500
700/700 [==============================] - 0s 14us/step - loss: 0.4665 - acc: 0.7700
Epoch 331/1500
700/700 [==============================] - 0s 14us/step - loss: 0.4632 - acc: 0.7714
Epoch 332/1500
700/700 [==============================] - 0s 14us/step - loss: 0.4622 - acc: 0.7714
Epoch 333/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4571 - acc: 0.7871
Epoch 334/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4580 - acc: 0.7814
Epoch 335/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4621 - acc: 0.7857
Epoch 336/1500
700/700 [==============================] - 0s 14us/step - loss: 0.4620 - acc: 0.7814
Epoch 337/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4618 - acc: 0.7757
Epoch 338/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4608 - acc: 0.7786
Epoch 339/1500


700/700 [==============================] - 0s 11us/step - loss: 0.4473 - acc: 0.7971
Epoch 412/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4394 - acc: 0.8057
Epoch 413/1500
700/700 [==============================] - 0s 14us/step - loss: 0.4392 - acc: 0.7900
Epoch 414/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4399 - acc: 0.7914
Epoch 415/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4439 - acc: 0.7900
Epoch 416/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4419 - acc: 0.7914
Epoch 417/1500
700/700 [==============================] - 0s 4us/step - loss: 0.4441 - acc: 0.7900
Epoch 418/1500
700/700 [==============================] - 0s 22us/step - loss: 0.4482 - acc: 0.7814
Epoch 419/1500
700/700 [==============================] - 0s 0us/step - loss: 0.4388 - acc: 0.7929
Epoch 420/1500
700/700 [==============================] - 0s 29us/step - loss: 0.4407 - acc: 0.7900
Epoch 421/1500
70

700/700 [==============================] - 0s 14us/step - loss: 0.4317 - acc: 0.7871
Epoch 494/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4322 - acc: 0.7943
Epoch 495/1500
700/700 [==============================] - 0s 14us/step - loss: 0.4413 - acc: 0.7857
Epoch 496/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4324 - acc: 0.7814
Epoch 497/1500
700/700 [==============================] - 0s 14us/step - loss: 0.4381 - acc: 0.7929
Epoch 498/1500
700/700 [==============================] - 0s 14us/step - loss: 0.4337 - acc: 0.7871
Epoch 499/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4407 - acc: 0.7871
Epoch 500/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4290 - acc: 0.7957
Epoch 501/1500
700/700 [==============================] - 0s 14us/step - loss: 0.4298 - acc: 0.8014
Epoch 502/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4305 - acc: 0.7929
Epoch 503/1500


700/700 [==============================] - 0s 11us/step - loss: 0.4364 - acc: 0.7900
Epoch 576/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4209 - acc: 0.7986
Epoch 577/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4225 - acc: 0.7914
Epoch 578/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4364 - acc: 0.7871
Epoch 579/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4222 - acc: 0.7914
Epoch 580/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4194 - acc: 0.8000
Epoch 581/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4205 - acc: 0.7957
Epoch 582/1500
700/700 [==============================] - 0s 14us/step - loss: 0.4193 - acc: 0.8014
Epoch 583/1500
700/700 [==============================] - 0s 4us/step - loss: 0.4230 - acc: 0.7971
Epoch 584/1500
700/700 [==============================] - 0s 0us/step - loss: 0.4296 - acc: 0.7857
Epoch 585/1500
70

700/700 [==============================] - 0s 11us/step - loss: 0.4211 - acc: 0.7986
Epoch 658/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4138 - acc: 0.8114
Epoch 659/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4164 - acc: 0.7957
Epoch 660/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4124 - acc: 0.7957
Epoch 661/1500
700/700 [==============================] - 0s 14us/step - loss: 0.4185 - acc: 0.7986
Epoch 662/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4458 - acc: 0.7757
Epoch 663/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4296 - acc: 0.7843
Epoch 664/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4316 - acc: 0.7900
Epoch 665/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4168 - acc: 0.7971
Epoch 666/1500
700/700 [==============================] - 0s 4us/step - loss: 0.4098 - acc: 0.8100
Epoch 667/1500
7

700/700 [==============================] - 0s 11us/step - loss: 0.4149 - acc: 0.8029
Epoch 740/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4165 - acc: 0.7957
Epoch 741/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4095 - acc: 0.7943
Epoch 742/1500
700/700 [==============================] - 0s 14us/step - loss: 0.4054 - acc: 0.8086
Epoch 743/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4100 - acc: 0.7986
Epoch 744/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4136 - acc: 0.8029
Epoch 745/1500
700/700 [==============================] - 0s 14us/step - loss: 0.4089 - acc: 0.8029
Epoch 746/1500
700/700 [==============================] - 0s 7us/step - loss: 0.4156 - acc: 0.8014
Epoch 747/1500
700/700 [==============================] - 0s 0us/step - loss: 0.4190 - acc: 0.7971
Epoch 748/1500
700/700 [==============================] - 0s 22us/step - loss: 0.4092 - acc: 0.8000
Epoch 749/1500
70

700/700 [==============================] - 0s 14us/step - loss: 0.4085 - acc: 0.8071
Epoch 822/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4021 - acc: 0.8100
Epoch 823/1500
700/700 [==============================] - 0s 14us/step - loss: 0.4034 - acc: 0.8129
Epoch 824/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4058 - acc: 0.8071
Epoch 825/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4026 - acc: 0.8129
Epoch 826/1500
700/700 [==============================] - 0s 14us/step - loss: 0.4042 - acc: 0.8014
Epoch 827/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4055 - acc: 0.7986
Epoch 828/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4064 - acc: 0.8057
Epoch 829/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4133 - acc: 0.7886
Epoch 830/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4074 - acc: 0.8029
Epoch 831/1500


700/700 [==============================] - 0s 11us/step - loss: 0.4153 - acc: 0.7914
Epoch 904/1500
700/700 [==============================] - 0s 11us/step - loss: 0.3972 - acc: 0.8029
Epoch 905/1500
700/700 [==============================] - 0s 14us/step - loss: 0.3989 - acc: 0.7986
Epoch 906/1500
700/700 [==============================] - 0s 14us/step - loss: 0.3982 - acc: 0.8071
Epoch 907/1500
700/700 [==============================] - 0s 14us/step - loss: 0.4011 - acc: 0.8100
Epoch 908/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4068 - acc: 0.7986
Epoch 909/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4030 - acc: 0.8043
Epoch 910/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4074 - acc: 0.8086
Epoch 911/1500
700/700 [==============================] - 0s 11us/step - loss: 0.3972 - acc: 0.8043
Epoch 912/1500
700/700 [==============================] - 0s 14us/step - loss: 0.4012 - acc: 0.8014
Epoch 913/1500


700/700 [==============================] - 0s 11us/step - loss: 0.3950 - acc: 0.8114
Epoch 986/1500
700/700 [==============================] - 0s 14us/step - loss: 0.4036 - acc: 0.7900
Epoch 987/1500
700/700 [==============================] - 0s 14us/step - loss: 0.4047 - acc: 0.8071
Epoch 988/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4005 - acc: 0.8043
Epoch 989/1500
700/700 [==============================] - 0s 14us/step - loss: 0.3932 - acc: 0.8071
Epoch 990/1500
700/700 [==============================] - 0s 18us/step - loss: 0.3947 - acc: 0.8143
Epoch 991/1500
700/700 [==============================] - 0s 11us/step - loss: 0.3939 - acc: 0.8057
Epoch 992/1500
700/700 [==============================] - 0s 14us/step - loss: 0.3945 - acc: 0.8143
Epoch 993/1500
700/700 [==============================] - 0s 14us/step - loss: 0.4170 - acc: 0.8000
Epoch 994/1500
700/700 [==============================] - 0s 4us/step - loss: 0.3997 - acc: 0.8114
Epoch 995/1500
7

700/700 [==============================] - 0s 11us/step - loss: 0.4056 - acc: 0.7914
Epoch 1067/1500
700/700 [==============================] - 0s 14us/step - loss: 0.4010 - acc: 0.8071
Epoch 1068/1500
700/700 [==============================] - 0s 11us/step - loss: 0.3920 - acc: 0.8129
Epoch 1069/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4084 - acc: 0.8014
Epoch 1070/1500
700/700 [==============================] - 0s 11us/step - loss: 0.3954 - acc: 0.8057
Epoch 1071/1500
700/700 [==============================] - 0s 14us/step - loss: 0.4026 - acc: 0.7957
Epoch 1072/1500
700/700 [==============================] - 0s 11us/step - loss: 0.3986 - acc: 0.8014
Epoch 1073/1500
700/700 [==============================] - 0s 11us/step - loss: 0.3957 - acc: 0.8086
Epoch 1074/1500
700/700 [==============================] - 0s 14us/step - loss: 0.4105 - acc: 0.7957
Epoch 1075/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4061 - acc: 0.8000
Epoch 

700/700 [==============================] - 0s 11us/step - loss: 0.3959 - acc: 0.8114
Epoch 1148/1500
700/700 [==============================] - 0s 14us/step - loss: 0.3930 - acc: 0.8043
Epoch 1149/1500
700/700 [==============================] - 0s 14us/step - loss: 0.3903 - acc: 0.8071
Epoch 1150/1500
700/700 [==============================] - 0s 14us/step - loss: 0.3917 - acc: 0.8057
Epoch 1151/1500
700/700 [==============================] - 0s 11us/step - loss: 0.3950 - acc: 0.8114
Epoch 1152/1500
700/700 [==============================] - 0s 7us/step - loss: 0.3948 - acc: 0.8086
Epoch 1153/1500
700/700 [==============================] - 0s 0us/step - loss: 0.3915 - acc: 0.8029
Epoch 1154/1500
700/700 [==============================] - 0s 22us/step - loss: 0.3952 - acc: 0.8043
Epoch 1155/1500
700/700 [==============================] - 0s 26us/step - loss: 0.3905 - acc: 0.8086
Epoch 1156/1500
700/700 [==============================] - 0s 14us/step - loss: 0.3884 - acc: 0.8071
Epoch 11

700/700 [==============================] - 0s 14us/step - loss: 0.3991 - acc: 0.8043
Epoch 1229/1500
700/700 [==============================] - 0s 11us/step - loss: 0.3920 - acc: 0.8100
Epoch 1230/1500
700/700 [==============================] - 0s 14us/step - loss: 0.3904 - acc: 0.8114
Epoch 1231/1500
700/700 [==============================] - 0s 14us/step - loss: 0.4045 - acc: 0.8014
Epoch 1232/1500
700/700 [==============================] - 0s 11us/step - loss: 0.3932 - acc: 0.7957
Epoch 1233/1500
700/700 [==============================] - 0s 14us/step - loss: 0.3946 - acc: 0.8014
Epoch 1234/1500
700/700 [==============================] - 0s 14us/step - loss: 0.3955 - acc: 0.8100
Epoch 1235/1500
700/700 [==============================] - 0s 14us/step - loss: 0.3962 - acc: 0.8086
Epoch 1236/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4030 - acc: 0.7986
Epoch 1237/1500
700/700 [==============================] - 0s 11us/step - loss: 0.3922 - acc: 0.8043
Epoch 

700/700 [==============================] - 0s 11us/step - loss: 0.3944 - acc: 0.8086
Epoch 1310/1500
700/700 [==============================] - 0s 11us/step - loss: 0.3972 - acc: 0.8014
Epoch 1311/1500
700/700 [==============================] - 0s 14us/step - loss: 0.3964 - acc: 0.8029
Epoch 1312/1500
700/700 [==============================] - 0s 14us/step - loss: 0.3873 - acc: 0.8071
Epoch 1313/1500
700/700 [==============================] - 0s 11us/step - loss: 0.3972 - acc: 0.8029
Epoch 1314/1500
700/700 [==============================] - 0s 11us/step - loss: 0.3953 - acc: 0.8057
Epoch 1315/1500
700/700 [==============================] - 0s 11us/step - loss: 0.3886 - acc: 0.8129
Epoch 1316/1500
700/700 [==============================] - 0s 14us/step - loss: 0.3905 - acc: 0.8043
Epoch 1317/1500
700/700 [==============================] - 0s 14us/step - loss: 0.3891 - acc: 0.8000
Epoch 1318/1500
700/700 [==============================] - 0s 14us/step - loss: 0.3883 - acc: 0.8129
Epoch 

700/700 [==============================] - 0s 14us/step - loss: 0.3869 - acc: 0.8114
Epoch 1391/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4002 - acc: 0.8057
Epoch 1392/1500
700/700 [==============================] - 0s 14us/step - loss: 0.3898 - acc: 0.8043
Epoch 1393/1500
700/700 [==============================] - 0s 11us/step - loss: 0.3979 - acc: 0.8057
Epoch 1394/1500
700/700 [==============================] - 0s 11us/step - loss: 0.3947 - acc: 0.8043
Epoch 1395/1500
700/700 [==============================] - 0s 11us/step - loss: 0.3890 - acc: 0.8157
Epoch 1396/1500
700/700 [==============================] - 0s 11us/step - loss: 0.3877 - acc: 0.8086
Epoch 1397/1500
700/700 [==============================] - 0s 14us/step - loss: 0.3932 - acc: 0.7971
Epoch 1398/1500
700/700 [==============================] - 0s 14us/step - loss: 0.3912 - acc: 0.8114
Epoch 1399/1500
700/700 [==============================] - 0s 11us/step - loss: 0.3939 - acc: 0.8114
Epoch 

700/700 [==============================] - 0s 14us/step - loss: 0.3977 - acc: 0.7971
Epoch 1472/1500
700/700 [==============================] - 0s 14us/step - loss: 0.3903 - acc: 0.8114
Epoch 1473/1500
700/700 [==============================] - 0s 14us/step - loss: 0.3864 - acc: 0.8157
Epoch 1474/1500
700/700 [==============================] - 0s 11us/step - loss: 0.3913 - acc: 0.8071
Epoch 1475/1500
700/700 [==============================] - 0s 14us/step - loss: 0.3843 - acc: 0.8157
Epoch 1476/1500
700/700 [==============================] - 0s 11us/step - loss: 0.3972 - acc: 0.8086
Epoch 1477/1500
700/700 [==============================] - 0s 11us/step - loss: 0.4004 - acc: 0.8043
Epoch 1478/1500
700/700 [==============================] - 0s 7us/step - loss: 0.3901 - acc: 0.8129
Epoch 1479/1500
700/700 [==============================] - 0s 0us/step - loss: 0.3842 - acc: 0.8143
Epoch 1480/1500
700/700 [==============================] - 0s 29us/step - loss: 0.3872 - acc: 0.8100
Epoch 14

In [12]:
scores=model.evaluate(x_test, y_test)
print("%s: %.2f%%" %(model.metrics_names[1],scores[1]*100))

68/68 [==============================] - 0s 229us/step
acc: 70.59%


In [13]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.preprocessing.image import ImageDataGenerator

np.random.seed(3)

In [15]:
train_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
        'warehouse/handwriting_shape/train',
        target_size=(24,24),
        batch_size=3,
        class_mode='categorical')

test_datagen = ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
        'warehouse/handwriting_shape/test',
        target_size=(24,24),
        batch_size=3,
        class_mode='categorical')

Found 45 images belonging to 3 classes.
Found 15 images belonging to 3 classes.


In [16]:
model=Sequential()
model.add(Conv2D(32,kernel_size=(3,3),activation='relu',input_shape=(24,24,3)))
model.add(Conv2D(64,(3,3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(128,activation='relu'))
model.add(Dense(3, activation='softmax'))

In [17]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [19]:
model.fit_generator(train_generator,steps_per_epoch=15,epochs=50,
                   validation_data=test_generator, validation_steps=5)

Epoch 1/50
15/15 [==============================] - 2s 155ms/step - loss: 0.7124 - acc: 0.6667 - val_loss: 0.3152 - val_acc: 0.9333
Epoch 2/50
15/15 [==============================] - 2s 104ms/step - loss: 0.1004 - acc: 0.9778 - val_loss: 0.0586 - val_acc: 1.0000
Epoch 3/50
15/15 [==============================] - 1s 96ms/step - loss: 0.0092 - acc: 1.0000 - val_loss: 0.0560 - val_acc: 1.0000
Epoch 4/50
15/15 [==============================] - 1s 89ms/step - loss: 0.0015 - acc: 1.0000 - val_loss: 0.0323 - val_acc: 1.0000
Epoch 5/50
15/15 [==============================] - 1s 99ms/step - loss: 5.0519e-04 - acc: 1.0000 - val_loss: 0.0312 - val_acc: 1.0000
Epoch 6/50
15/15 [==============================] - 2s 114ms/step - loss: 2.9638e-04 - acc: 1.0000 - val_loss: 0.0339 - val_acc: 1.0000
Epoch 7/50
15/15 [==============================] - 1s 96ms/step - loss: 2.1691e-04 - acc: 1.0000 - val_loss: 0.0349 - val_acc: 1.0000
Epoch 8/50
15/15 [==============================] - 1s 97ms/step - l

In [20]:
print("-- Evaluate --")
scores = model.evaluate_generator(test_generator, steps=5)
print("%s: %.2f%%" %(model.metrics_names[1],scores[1]*100))

-- Evaluate --
acc: 100.00%


In [21]:
print("--Predict--")
output = model.predict_generator(test_generator, steps=5)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(test_generator.class_indices)
print(output)

--Predict--
{'circle': 0, 'rectangle': 1, 'triangle': 2}
[[0.000 1.000 0.000]
 [0.000 1.000 0.000]
 [0.000 0.000 1.000]
 [0.000 0.000 1.000]
 [1.000 0.000 0.000]
 [1.000 0.000 0.000]
 [0.000 0.000 1.000]
 [0.991 0.000 0.009]
 [1.000 0.000 0.000]
 [0.000 1.000 0.000]
 [0.348 0.387 0.265]
 [0.000 0.000 1.000]
 [0.000 0.007 0.993]
 [1.000 0.000 0.000]
 [0.000 1.000 0.000]]


In [22]:
from keras.applications.vgg16 import VGG16
model=VGG16()
print(model.summary())

553467904/553467096 [==============================] - 85s 0us/step
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 224, 224, 3)       0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_p

In [25]:
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
from keras.applications.vgg16 import preprocess_input
from keras.applications.vgg16 import decode_predictions
from keras.applications.vgg16 import VGG16

model = VGG16()
image = load_img('cat.jpg', target_size=(224,224))
image = img_to_array(image)
print("image shape : ", image.shape)
image = image.reshape((1, image.shape[0], image.shape[1], image.shape[2]))
print("processed image shape : ", image.shape)
iamge = preprocess_input(image)

image shape :  (224, 224, 3)
processed image shape :  (1, 224, 224, 3)


In [28]:
yhat = model.predict(image)
label = decode_predictions(yhat)
label = label[0][0]
print('%s (%.2f%%)'%(label[1], label[2]*100))
print(label)

Egyptian_cat (92.03%)
('n02124075', 'Egyptian_cat', 0.9203331)
